---
# FIXME: This uses podman, so does not work on cockpit-11 right now
- hosts: tag_ServiceComponent_Images
  gather_facts: false

  tasks:
  - name: "Upload images service installation script"
    copy:
      src: "{{ playbook_dir }}/../../images/install-service"
      dest: /run/install-service
      mode: preserve

  - name: "Set up systemd service for cockpit/images"
    command: /run/install-service
