---
- hosts: e2e

  tasks:
  - name: Setup NTP config
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
      restart ntpd

  handlers:
  - name: restart ntpd
    service: name=ntpd state=restarted

