---
- name: Set up host OS
  hosts: e2e
  gather_facts: false
  roles:
  - role: users
    vars:
      user: root

  tasks:
  - name: Disallow root logins with password
    file:
      path: /etc/ssh/sshd_config.d/01-permitrootlogin.conf
      state: absent

  - name: Lock root account password
    command: passwd -l root

  - name: Disable zezere service
    service:
      name: zezere_ignition.timer
      state: stopped
      enabled: no

  - name: Disable zezere banner
    service:
      name: zezere_ignition_banner.service
      state: stopped
      enabled: no

  - name: Drop default NTP servers
    lineinfile:
      path: /etc/chrony.conf
      regexp: '^pool'
      state: absent
    register: ntp_1

  - name: Add Red Hat internal NTP server
    lineinfile:
      path: /etc/chrony.conf
      regexp: '^server'
      line: server clock.corp.redhat.com iburst
    register: ntp_2

  - name: Restart chrony on changes
    service:
      name: chronyd
      state: restarted
    when: ntp_1.changed or ntp_2.changed

  - name: Disable unconnected network interfaces to avoid NM-wait-online timeout
    copy:
      dest: /etc/NetworkManager/conf.d/disabled-ifaces.conf
      mode: 0644
      content: |
        [keyfile]
        unmanaged-devices=interface-name:eno*,interface-name:enp3s0f3
    register: disable_ifaces

  # github.com has an obnoxiously short TTL of a minute
  - name: set minimum TTL for local DNS cache
    copy:
      dest: /etc/NetworkManager/dnsmasq.d/longer-cache.conf
      mode: 0644
      content: |
        min-cache-ttl=3600

  - name: enable dnsmasq in NetworkManager
    copy:
      dest: /etc/NetworkManager/conf.d/dns.conf
      mode: 0644
      content: |
        [main]
        dns=dnsmasq
    register: nm_dnsmasq

  - name: Reload NetworkManager for configuration changes
    service:
      name: NetworkManager
      state: reloaded
    when: nm_dnsmasq.changed or disable_ifaces.changed

- name: Set up tasks runner
  hosts: e2e
  gather_facts: false
  roles:
    - ci-data-cache
    - install-secrets-dir
    - tasks-systemd

- name: Set up image server
  hosts: e2e_s3
  gather_facts: false
  roles:
    - s3-systemd
