---
- name: Set up host OS
  hosts: e2e
  gather_facts: false
  roles:
  - role: users
    vars:
      user: root

  tasks:
  - name: Disallow root logins with password
    file:
      path: /etc/ssh/sshd_config.d/01-permitrootlogin.conf
      state: absent

  - name: Lock root account password
    command: passwd -l root

  - name: Disable zezere service
    service:
      name: zezere_ignition.timer
      state: stopped
      enabled: no

  - name: Disable zezere banner
    service:
      name: zezere_ignition_banner.service
      state: stopped
      enabled: no

  # github.com has an obnoxiously short TTL of a minute
  - name: set minimum TTL for local DNS cache
    copy:
      dest: /etc/NetworkManager/dnsmasq.d/longer-cache.conf
      mode: 0644
      content: |
        min-cache-ttl=3600

  - name: enable dnsmasq in NetworkManager
    copy:
      dest: /etc/NetworkManager/conf.d/dns.conf
      mode: 0644
      content: |
        [main]
        dns=dnsmasq
    register: nm_dnsmasq

  - name: Reload NetworkManager for dnsmasq configuration change
    service:
      name: NetworkManager
      state: reloaded
    when: nm_dnsmasq.changed

- name: Set up tasks runner
  hosts: e2e
  gather_facts: false
  roles:
    - ci-data-cache
    - install-secrets-dir
    - tasks-systemd

- name: Set up image server
  hosts: e2e_s3
  gather_facts: false
  roles:
    - s3-systemd
