#!/usr/bin/python3

import argparse
import textwrap
import re

pattern = re.compile(rb'(^menuentry.*{\n(\t[^\n]*\n)+}\n){2}submenu.*{\n(\t[^\n]*\n)+}\n', re.MULTILINE)

parser = argparse.ArgumentParser()
parser.add_argument('--ks', required=True)
parser.add_argument('input')
parser.add_argument('output')
args = parser.parse_args()

with open(args.input, 'rb') as original:
    data = bytearray(original.read())

for hit in pattern.finditer(data):
    start, end = hit.span()
    size = end - start

    print(f'Hacking {size} bytes at [{start}, {end}):')

    replacement = textwrap.dedent('''
        menuentry 'Skip' {
        }
        menuentry 'Install with kickstart' {
            linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=Fedora-iot-ostree-x86_64-36 inst.ks=%s
            initrdefi /images/pxeboot/initrd.img
        }
    ''' % (args.ks,)).encode('ascii')

    print('--- BEFORE ---')
    print(data[start:end].decode('ascii'))
    print('--- AFTER ---')
    print(replacement.decode('ascii'))

    replacement += b'\n' * (size - len(replacement))
    assert len(replacement) == size
    data[start:end] = replacement

with open(args.output, 'wb') as hacked:
    hacked.write(data)
