#!/bin/sh

# Hack a Fedora IoT installer ISO and serve it over NFS along with a kickstart file
# This process worked for Fedora-IoT-ostree-x86_64-36-20220523.0.iso but may need adjusting for others
#
# Before you do anything, download a Fedora IoT ISO from
#
#    https://download.fedoraproject.org/pub/alt/iot/36/IoT/x86_64/iso/
#
# and drop it in this directory.  Then run this script.

set -eu

my_ip="$(hostname -I | cut -f1 -d' ')"
dir="$(realpath -m $0/..)"

test -f iot.iso || ./hack-iso --ks=nfs:${my_ip}:/install/ks.cfg Fedora-IoT-*.iso iot.iso

echo "./reboot-into-iso idrac-[hostname] ${my_ip}:/install/iot.iso"

podman run \
    --rm \
    --network=host \
    --name=nfs \
    --privileged \
    --volume="${dir}":/install:ro \
    --env=NFS_EXPORT_0='/install *(ro)' \
    docker.io/erichough/nfs-server
