version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    labels:
      - "bot"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
