#!/bin/sh -euf
#
# release-bodhi
#
# A script that does a Bodhi update request.
#
# Arguments are described here. Most arguments have an equivalent envvar.
#
# -m srpm    RELEASE_SRPM=srpm      Path to SRPM
# -q         RELEASE_QUIET=1        Make output more quiet
# -x         RELEASE_TRANSACTION=1  SIGSTOP before pushing the dist-git commit
# -v         RELEASE_VERBOSE=1      Make output more verbose
#

set -euf

# Various arguments
TRANSACTION=${RELEASE_TRANSACTION:-0}
QUIET=${RELEASE_QUIET:-0}
VERBOSE=${RELEASE_VERBOSE:-0}
SRPM=${RELEASE_SRPM:-$PWD/srpm}

# Other globals
CLEANUP=""

usage()
{
    echo "usage: release-bodhi [-qvx] [-s SRPM]" >&2
    exit ${1-2}
}

trace()
{
    if [ $QUIET -eq 0 ]; then
        echo "> $@" >&2
    fi
}

message()
{
    echo "release-bodhi: $@" >&2
}

readlink_or()
{
    if ! readlink "$1"; then
        echo "$1"
    fi
}

prepare()
{
}

commit()
(
    bodhi --new --type=enhancement --notes="$notes" --close-bugs --stablekarma=3 --unstablekarma=1 --request=stable
)

while getopts "f:kp:s:t:qvx" opt; do
    case "$opt" in
    f)
        TARBALL="$OPTARG"
        ;;
    k)
        CONTINUE=1
        ;;
    p)
        PACKAGE="$OPTARG"
        ;;
    s)
        SPEC="$OPTARG"
        ;;
    t)
        TAG="$OPTARG"
        ;;
    q)
        QUIET=1
        VERBOSE=0
        ;;
    v)
        QUIET=0
        VERBOSE=1
        ;;
    x)
        TRANSACTION=1
        ;;
    -)
        break
        ;;
    *)
        usage
        ;;
    esac
done

shift $(expr $OPTIND - 1)

if [ $# -ne 1 ]; then
    usage
fi

BRANCH="$1"

# The tag for the release
if [ -z "$TAG" ]; then
    TAG=$(git describe --abbrev=0)
    if [ -z "$TAG" ]; then
        message "could not find a tag to release"
        exit 2
    fi
fi

if [ -z "$PACKAGE" ]; then
    message "no package specified"
    exit 2
fi

if [ -z "$SPEC" ]; then
    message "no spec source file specified"
    exit 2
elif [ ! -f "$SPEC" ]; then
    message "spec source file not found: $SPEC"
    exit 1
fi

if [ -z "$TARBALL" ]; then
    message "no tarball input specified"
    exit 2
elif [ ! -f "$TARBALL" ]; then
    message "tarball source not found: $TARBALL"
    exit 1
fi

prepare

if [ $TRANSACTION -eq 1 ]; then
    kill -STOP $$
fi

commit
