#!/bin/sh -euf

set -euf

. $(dirname $0)/build-common

prepare()
(
    # Prepare stage input required
    require $GITDIR $TARBALL $GITDIR/tools/cockpit.spec

    if [ $# -ne 1 ]; then
        usage
    fi


    if [ ! -d $KOJIDIR ]; then
        git clone "$KOJIURL" $KOJIDIR
    else
        cd $KOJIDIR
        git fetch origin
        git reset --hard HEAD
    fi

    cd $KOJIDIR
    git checkout $1
    git reset --hard $1

    # Update the spec file
    ( cd $GITDIR && update-spec $KOJIDIR/cockpit.spec )

    # Bring over the sources
    tarball=$(readlink $TARBALL)
    tarname=$(basename $tarball)
    cp $tarball .
    md5sum $tarname > sources
    echo "/$tarname" >> .gitignore

    # Commit all of that
    git add cockpit.spec sources .gitignore
    ( cd $GITDIR && tag-message ) | git commit -F -

    # Make an SRPM out of that
    tmpfile=$(mktemp .fedpkg-srpm.XXXXXX)
    fedpkg srpm | tee $tmpfile
    srpm=$(sed -n 's/Wrote: \(.\+\.src\.rpm\)$/\1/p' $tmpfile)
    rm $tmpfile

    # Build it in brew
    fedpkg scratch-build --srpm=$srpm
)

commit()
(
    exit 2
    # Prepare stage input required
    require $TARBALL $GITDIR/tools/cockpit.spec

    cd $KOJIDIR

    # Upload the sources
    tarball=$(readlink $TARBALL)
    fedpkg new-sources $(basename $tarball)
    git reset --hard HEAD  # Undo any silliness above

    # Push the changes
    git push origin $1
    fedpkg build
)

usage()
{
    echo "usage: build-koji prepare <ver>" >&2
    exit 2
}

while getopts "" opt; do
    case "$opt" in
    -)
        break
        ;;
    *)
        usage
        ;;
    esac
done

shift $(expr $OPTIND - 1)
build "$@"
