#!/bin/sh -euf

set -euf

. $(dirname $0)/build-common

prepare()
(
    # No prepare stage input
    require

    if [ ! -d $GITDIR ]; then
        git clone "$GITURL" $GITDIR
    else
        cd $GITDIR
        git fetch origin
        git reset --hard HEAD
    fi

    cd $GITDIR

    if [ $# -eq 0 ]; then
        tag=$(git describe --abbrev=0)
    else
        tag="$1"
    fi

    if git show-ref --verify --quiet refs/heads/release-$tag; then
	git checkout master
    	git branch -D release-$tag
    fi
    git branch release-$tag $tag
    git checkout release-$tag

    mkdir -p $GITDIR/build
    rm -rf $GITDIR/build/*
    cd $GITDIR/build
    ../autogen.sh --prefix=/usr
    make -j1 distcheck

    cd $GITDIR
    ln -snf $GITDIR/build/cockpit-$tag.tar.bz2 $TARBALL

    # This prepare stage output:
    require $GITDIR $TARBALL
)

usage()
{
    echo "usage: build-git prepare <tag>" >&2
    exit 2
}

while getopts "" opt; do
    case "$opt" in
    -)
        break
        ;;
    *)
        usage
        ;;
    esac
done

shift $(expr $OPTIND - 1)
build "$@"
