#!/bin/sh
set -eu

IMAGE=$1
[ -n "${DOCKER:-}" ] || DOCKER=$(which podman docker 2>/dev/null | head -n1)
ID=$($DOCKER images -q $IMAGE:latest | head -n1)

TAGS=$($DOCKER images --format '{{.Tag}}   {{.ID}}' $IMAGE | sort -u | grep $ID | awk '{print $1}')
if [ $(echo "$TAGS" | wc -w) -ne "2" ]; then
    echo "Expected exactly two tags for the image to push: latest and one other"
    exit 1
fi
for PUSHTAG in $TAGS; do
    $DOCKER push "$IMAGE:$PUSHTAG"
done
