#!/bin/sh -euf
#
# release-github
#
# A script that creates a GitHub release with a tarball from a git tag.
# Run it from within a GitHub checkout.
#
# $ git tag -as 0.55
# $ make distcheck
# $ release-github -f package-0.55.tbz
#
# The tag will be pushed if it does not exist online. If specified, the
# tarball will be attached to the release. If the tarball is a symlink
# it will be resolved to its actual file name.
#
# The current account's SSH keys will be used for the tag push, and the
# file ~/.config/github-token will be read as a GitHub API token.
#
# Arguments are described here. Most arguments have an equivalent envvar.
#
# -f tgz     RELEASE_TARBALL=tbz    The tarball to upload
#                                   default: no file attachment
# -t 0.X     RELEASE_TAG=0.X        The tag to create release from
#                                   default: latest tag
# -o origin  RELEASE_ORIGIN=origin  Git remote origin to lookup as github repo
#                                   default: origin
# -q         RELEASE_QUIET=1        Make output more quiet
# -x         RELEASE_TRANSACTION=1  SIGSTOP before publishing the Github draft
# -v         RELEASE_VERBOSE=1      Make output more verbose
# -z         RELEASE_CREDCHECK=1    Check credentials only
#

set -euf

# Arguments
VERBOSE="${RELEASE_VERBOSE:-0}"
QUIET="${RELEASE_QUIET:-0}"
TRANSACTION="${RELEASE_TRANSACTION:-0}"
ORIGIN="${RELEASE_ORIGIN:-origin}"
TARBALL="${RELEASE_TARBALL:-}"
TAG="${RELEASE_TAG:-}"
CREDCHECK=${RELEASE_CREDCHECK:-0}

# Other globals
TOKEN="${GITHUB_TOKEN:-}"
REPO=
REPO_PATH=
RELEASE=
CLEANUP=

usage()
{
    echo "usage: release-github [-qvxz] [-t TAG] [-o ORIGIN] [-f TARBALL]" >&2
    exit ${1-2}
}

trace()
{
    if [ $QUIET -eq 0 ]; then
        echo "> $@" >&2
    fi
}

message()
{
    echo "release-github: $@" >&2
}

json_escape()
{
    # Escape quotes, backslashes and new lines
    sed -e 's/[\\"]/\\\0/g' -e 's/$/\\n/g'
}

trim_contents()
{
    # Remove line with just tag name. Remove signature
    sed -e '/^\s*'$TAG'\s*$/d' -e '/-----BEGIN/,/-----END/d'
}

run_curl()
{
    local arg

    if [ $VERBOSE -eq 1 ]; then
        arg="--verbose"
    elif [ $QUIET -eq 1 ]; then
        arg="-s"
    else
        arg=""
    fi

    if ! curl $arg -S --fail -H "Authorization: token $TOKEN" "$@"; then
        message "github api call failed"
        exit 1
    fi
}

readlink_or()
{
    if ! readlink "$1"; then
        echo "$1"
    fi
}

cred_check ()
{
    "$(dirname $0)/check-git-rw" git@github.com "$REPO_PATH"
    run_curl --output /dev/null -s https://api.github.com$REPO/collaborators
}

prepare()
{
    local tmpfile body upload uplog base progress

    tmpfile=$(mktemp .github-draft.XXXXXX.json)

    # The body of the email ready as a JSON string
    body="$(git for-each-ref --format='%(contents)' "refs/tags/$TAG" | trim_contents | json_escape)"

    trace "Creating release draft: $TAG"

    # Create the release via the Github API
    printf '{"tag_name": "%s", "name": "%s", "draft": true, "body": "%s" }\n' \
        "$TAG" "$TAG" "$body" |
        run_curl -s --data @- --output $tmpfile https://api.github.com$REPO/releases

    # Remove this file later
    CLEANUP="$CLEANUP $tmpfile"

    # The release URL for later commit
    RELEASE=$(sed -n 's/.*"url"\s*:\s*"\([^"]*\).*/\1/p' $tmpfile | head -n 1)

    if [ -n "$TARBALL" ]; then
        trace "Uploading file: $TARBALL"

        # Figure out the URL to upload to
        upload=$(sed -n 's/.*"upload_url"\s*:\s*"\([^{"]*\).*/\1/p' $tmpfile)

        # And do the actual upload via the Github API
        uplog=$(mktemp .github-upload.XXXXXX.json)

        if [ -n "$QUIET" ]; then
            progress="--progress-bar"
        fi

        ball="$(readlink_or $TARBALL)"
        base="$(basename $ball)"
        run_curl --data-binary @$TARBALL --progress-bar --output $uplog \
             -H "Accept: application/vnd.github.manifold-preview" \
             -H "Content-Type: application/x-bz2" \
            "$upload?name=$base"

        # Remove this file later
        CLEANUP="$CLEANUP $uplog"
    fi
}

commit()
{
    tmpfile=$(mktemp .github-publish.XXXXXX.json)

    trace "Pushing tag: $TAG"
    git push "$ORIGIN" "$TAG"

    trace "Publishing draft: $TAG"

    printf '{"draft": false}\n' |
        run_curl -s --data @- --output $tmpfile --request PATCH $RELEASE

    # Remove all the temporary files on success
    rm $CLEANUP $tmpfile
}

while getopts "f:o:t:qvxz" opt; do
    case "$opt" in
    f)
        TARBALL="$OPTARG"
        ;;
    o)
        ORIGIN="$OPTARG"
        ;;
    t)
        TAG="$OPTARG"
        ;;
    q)
        QUIET=1
        VERBOSE=0
        ;;
    v)
        VERBOSE=1
        QUIET=0
        ;;
    x)
        TRANSACTION=1
        ;;
    z)
        CREDCHECK=1
        ;;
    -)
        break
        ;;
    *)
        usage 0
        ;;
    esac
done

shift $(expr $OPTIND - 1)

if [ $# -ne 0 ]; then
    usage
fi

# A github.com repos path like /repos/:ownser/:repo
REPO=$(LC_ALL=C git remote show -n $ORIGIN |
    sed -n 's/.*Push.*github.com[:\/]\(.*\+\)\/\([^\.]\+\).*/\/repos\/\1\/\2/p')
REPO_PATH=$(LC_ALL=C git remote show -n $ORIGIN |
    sed -n 's/.*Push.*github.com[:\/]\(.*\+\)\/\([^\.]\+\).*/\1\/\2/p')

if [ -z "$REPO" ]; then
    message "could not find github remote: $ORIGIN"
    exit 1
fi

# The token for github access
if [ -z "$TOKEN" ]; then
    TOKEN=$(cat ~/.config/github-token)
fi

if [ $CREDCHECK -eq 1 ]; then
    cred_check
    exit 0
fi

# The tag for the release
if [ -z "$TAG" ]; then
    TAG=$(git describe --abbrev=0)
    if [ -z "$TAG" ]; then
        message "could not find a tag to release"
        exit 1
    fi
fi

if [ -n "$TARBALL" -a ! -f "$TARBALL" ]; then
    message "tarball source not found: $TARBALL"
    exit 1
fi

prepare

if [ $TRANSACTION -eq 1 ]; then
    kill -STOP $$
fi

commit
