#!/bin/sh

sudo docker run -ti \
	-v $PWD:/usr/local/bin \
	-v ~/.fedora.cert:/root/.fedora.cert \
	-v ~/.fedora-server-ca.cert:/root/.fedora-server-ca.cert \
	-v ~/.gitconfig:/root/.gitconfig \
	-v ~/.config/copr:/root/.config/copr \
	-v ~/.config/github-token:/root/.config/github-token \
	-v $SSH_AUTH_SOCK:/root/ssh-auth-sock \
	-e SSH_AUTH_SOCK=/root/ssh-auth-sock \
	cockpituous /bin/bash
