#!/bin/sh -euf

set -euf

. $(dirname $0)/build-common

dash_bullets()
{
        sed -e 's/^* /- /' \
            -e 's/^ * /- /' \
            -e 's/^[^ *-]/- \0/'
}

format_date()
{
        LC_ALL=C date --date=$1 '+%a %b %d %Y'
}

changelog()
{
    local tagdate tagauthor tagemail tagbody
    eval $(git for-each-ref --shell --format='
tagdate=%(taggerdate:short)
tagauthor=%(taggername)
tagemail=%(taggeremail)' refs/tags/$1)
    tagbody="$(git for-each-ref --format='%(contents)' refs/tags/$1 | no_signature | dash_bullets)"
    tagdate="$(format_date $tagdate)"
    printf "* %s %s %s - %s-%s\n%s\n\n" "$tagdate" "$tagauthor" "$tagemail" "$1" "$2" "$tagbody"
}

if [ $# -ne 1 ]; then
    echo "usage: update-spec spec" >&2
    exit 2
fi

SPEC="$1"
TAG=$(git describe --abbrev=0)
REL=1

if grep -q "$TAG-$REL" "$SPEC"; then
    warning "$spec: already has $TAG-$REL present"
    exit 1
fi

tmpfile=$(mktemp .changelog.XXXXXX)
printf "%%changelog\n" >> $tmpfile
changelog $TAG $REL >> $tmpfile
sed '1,/%changelog/d' "$SPEC" >> $tmpfile


sed -e "1s/^/%define tag $TAG\n%define rel $REL\n/" \
        -e "/%changelog/r $tmpfile" \
        -e "/%changelog/,\$d" \
        tools/cockpit.spec > "$SPEC"

rm $tmpfile
