- name: Set up nested KVM
  shell: |
    echo "options kvm-intel nested=1" > /etc/modprobe.d/kvm-intel.conf
    echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666"' > /etc/udev/rules.d/80-kvm.rules
    udevadm control --reload
    rmmod kvm_intel
    modprobe kvm_intel || true
  args:
    creates: /etc/modprobe.d/kvm-intel.conf
