#!/bin/sh
# Run this in a home directory with all credentials; write OpenShift secret
# volumes YAML definitions to stdout
# https://docs.openshift.com/container-platform/3.9/dev_guide/secrets.html
set -eu

BASE=${1:-/var/lib/cockpit-secrets}

cat <<EOF
---
apiVersion: v1
kind: List
items:
EOF

# tasks secrets
cat <<EOF
- apiVersion: v1
  kind: Secret
  metadata:
    name: cockpit-tasks-secrets
  data:
EOF
cd "$BASE/tasks"
for f in $(find -type f -o -type l); do
    printf '    %s: %s\n' "$(echo $f | sed 's!^./!!; s!/!--!g')" "$(base64 --wrap=0 $f)"
done

# webhook secrets
cat <<EOF
- apiVersion: v1
  kind: Secret
  metadata:
    name: webhook-secrets
  data:
EOF
cd "$BASE/webhook"
for f in $(find -type f -o -type l); do
    printf '    %s: %s\n' "$(echo $f | sed 's!^./!!; s!/!--!g')" "$(base64 --wrap=0 $f)"
done

# metrics secrets
cat <<EOF
- apiVersion: v1
  kind: Secret
  metadata:
    name: metrics-secrets
  data:
EOF
cd "$BASE/metrics"
for f in $(find -type f -o -type l); do
    printf '    %s: %s\n' "$(echo -e $f | sed 's!^./!!; s!/!--!g')" "$(tr -d '\n' < $f | base64 --wrap=0)"
done
