#!/bin/sh
# Run this in a home directory with all credentials; write OpenShift secret
# volumes YAML definitions to stdout
# https://docs.openshift.com/container-platform/3.9/dev_guide/secrets.html
set -eu

BASE=${1:-/var/lib/cockpit-secrets}

# tasks secrets
cat <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: cockpit-tasks-secrets
data:
EOF
cd "$BASE/tasks"
# This intentionally does not capture subdirs. As OpenShift secret volumes don't have subdirectories,
# these need to be created as a separate volume if and when we ever need that.
for f in $(find -maxdepth 1 -type f -o -type l); do
    printf '  %s: %s\n' "${f#./}" "$(base64 --wrap=0 $f)"
done

# S3 keys secrets
cat <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: cockpit-s3-secrets
data:
EOF
cd "$BASE/s3-keys"
for f in $(find -maxdepth 1 -type f -o -type l); do
    printf '  %s: %s\n' "${f#./}" "$(base64 --wrap=0 $f)"
done

# local S3 image cache server secrets
cat <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: cockpit-s3-server-secrets
data:
EOF
cd "$BASE/s3-server"
for f in $(find -maxdepth 1 -type f -o -type l); do
    printf '  %s: %s\n' "${f#./}" "$(base64 --wrap=0 $f)"
done

# webhook secrets
cat <<EOF

---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-secrets
data:
EOF
cd "$BASE/webhook"
for f in $(find -maxdepth 1 -type f -o -type l); do
    printf '  %s: %s\n' "${f#./}" "$(base64 --wrap=0 $f)"
done

# metrics secrets
cat <<EOF

---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-secrets
data:
EOF
cd "$BASE/metrics"
for f in $(find -maxdepth 1 -type f -o -type l); do
    printf '  %s: %s\n' "${f#./}" "$(tr -d '\n' < $f | base64 --wrap=0)"
done
