#!/bin/sh

set -euf

BASE=${1:-./secrets}

secrets()
{
    local first file
    printf '{ "apiVersion": "v1", "kind": "Secret", "metadata": { "name": "cockpit-tasks-secrets" }, "data": {\n'

    first="yes"
    find "$BASE" -type f | while read file; do
        if [ $first != "yes" ]; then
            printf ',\n'
        fi
        printf '\t"%s": "%s"' "$(basename $file)" "$(base64 --wrap=0 $file)"
        first="no"
    done

    printf '\n} }\n'
}

secrets
