---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: bos-tasks
  spec:
    replicas: 1
    selector:
      infra: cockpit-tasks
    template:
      metadata:
        labels:
          infra: cockpit-tasks
      spec:
        containers:
        - name: cockpit-tasks
          image: docker.io/cockpit/tasks
          securityContext:
            runAsUser: 1111
            hostNetwork: false
          env:
          - name: TEST_JOBS
            value: '8'
          - name: TEST_PUBLISH
            value: sink
          volumeMounts:
          - name: secrets
            mountPath: "/secrets"
            readOnly: true
          - name: webhook-secrets
            mountPath: /run/secrets/webhook
            readOnly: true
          - name: cache
            mountPath: "/cache"
          - name: shm
            mountPath: "/dev/shm"
          - name: tmp
            mountPath: "/tmp"
        - name: cockpit-images
          image: docker.io/cockpit/images
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          volumeMounts:
          - name: secrets
            mountPath: "/secrets"
            readOnly: true
          - name: cache
            mountPath: "/cache"
        volumes:
        - name: secrets
          secret:
            secretName: cockpit-tasks-secrets
        - name: webhook-secrets
          secret:
            secretName: webhook-secrets
        - name: cache
          hostPath:
            path: "/var/cache/cockpit-tasks"
        - name: shm
          emptyDir:
            medium: Memory
        - name: tmp
          emptyDir: {}
        serviceAccountName: cockpituous
- apiVersion: v1
  kind: Service
  metadata:
    name: cockpit-images
  spec:
    clusterIP: None
    selector:
      infra: cockpit-tasks
    ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
