---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: psi-tasks
  spec:
    replicas: 1
    selector:
      infra: cockpit-tasks
    template:
      metadata:
        labels:
          infra: cockpit-tasks
      spec:
        containers:
        - name: cockpit-tasks
          image: docker.io/cockpit/tasks
          env:
          - name: TEST_JOBS
            value: '8'
          - name: TEST_PUBLISH
            value: sink
          - name: AMQP_SERVER
            value: 'amqp-cockpit.apps.ci.centos.org:443'
          volumeMounts:
          - name: secrets
            mountPath: "/secrets"
            readOnly: true
          - name: webhook-secrets
            mountPath: /run/secrets/webhook
            readOnly: true
          - name: cache
            mountPath: "/cache"
          - name: images
            mountPath: "/cache/images"
          - name: shm
            mountPath: "/dev/shm"
          resources:
            requests:
              cpu: 7750m
            limits:
              cpu: 7750m
              memory: 16G
        volumes:
        - name: secrets
          secret:
            secretName: cockpit-tasks-secrets
        - name: webhook-secrets
          secret:
            secretName: webhook-secrets
        - name: cache
          emptyDir: {}
        - name: images
          persistentVolumeClaim:
            claimName: cockpit-images
        - name: shm
          emptyDir:
            medium: Memory
        - name: tmp
          emptyDir: {}
        nodeSelector:
          oci_kvm_hook: allowed
