FROM fedora:39
LABEL maintainer='cockpit-devel@lists.fedorahosted.org'

RUN dnf -y update && \
    dnf -y install --disablerepo=fedora-cisco-openh264 --setopt=install_weak_deps=False \
        'dnf-command(builddep)' \
        adobe-source-code-pro-fonts \
        byobu \
        chromium-headless \
        curl \
        dbus-daemon \
        dbus-glib \
        diffstat \
        expect \
        firefox \
        fpaste \
        gcc-c++ \
        genisoimage \
        git \
        gnupg \
        google-noto-cjk-fonts-common \
        intltool \
        jq \
        lcov \
        libXt \
        libappstream-glib \
        libvirt-client \
        libvirt-daemon-driver-qemu \
        libvirt-daemon-driver-storage-core \
        libvirt-python3 \
        nc \
        net-tools \
        nodejs-devel \
        npm \
        passwd \
        pigz \
        podman-remote \
        procps-ng \
        psmisc \
        python3 \
        python3-aiohttp+speedups \
        python3-aioresponses \
        python3-build \
        python3-flake8 \
        python3-mypy \
        python3-pika \
        python3-pillow \
        python3-pip \
        python3-pytest \
        python3-pytest-asyncio \
        python3-pytest-timeout \
        python3-pyyaml \
        python3-wheel \
        qemu-kvm-core \
        rpm-build \
        rpmdevtools \
        rsync \
        socat \
        strace \
        tar \
        valgrind \
        vim-enhanced \
        virt-install \
        && \
    curl -o /tmp/cockpit.spec -s https://raw.githubusercontent.com/cockpit-project/cockpit/main/tools/cockpit.spec && \
    dnf -y builddep --setopt=install_weak_deps=False /tmp/cockpit.spec && \
    rm /tmp/cockpit.spec && \
    dnf clean all && \
    pip install ruff

COPY cockpit-tasks install-service webhook github_handler.py /usr/local/bin/

RUN groupadd -g 1111 -r user && useradd -r -g user -u 1111 user --home-dir /work && \
    groupadd -g 1001 -r github && useradd -r --no-create-home -g github -u 1001 github && \
    mkdir -p /usr/local/bin /cache/images /cache/github && \
    mkdir -p /work/.ssh /work/.cache && \
    printf '[user]\n\t\nemail = cockpituous@cockpit-project.org\n\tname = Cockpituous\n[cockpit "bots"]\n\timages-data-dir = /cache/images\n' >/work/.gitconfig && \
    chmod g=u /etc/passwd && \
    chmod -R ugo+w /cache /work && \
    chown -R user:user /cache /work && \
    printf '[libdefaults]\ndefault_ccache_name = FILE:/tmp/krb5.ccache\n' > /etc/krb5.conf.d/0_file_ccache && \
    echo 'user ALL=NOPASSWD: /usr/bin/chmod 666 /dev/kvm' > /etc/sudoers.d/user-fix-kvm

ENV LANG=C.UTF-8 \
    TEST_OVERLAY_DIR=/tmp

VOLUME /cache/images

USER user
WORKDIR /work
