#!/bin/sh

set -e

# If first argument starts with a path no loop
loop=yes
case ${1-} in
    /*)
        loop=no
        ;;
esac

# Set to verbose when looping
if [ $loop = "yes" ]; then
    set -x
fi

# Make sure directory is writable
sudo chown user:user /images

if [ -n "$TMPDIR" ]; then
    mkdir -p "$TMPDIR"
    mkdir -p $TMPDIR/libvirt
    rm -rf /tmp/libvirt
    ln -snf $TMPDIR/libvirt /tmp/libvirt
fi

if [ ! -d cockpit ]; then
    sudo chown -R user /build
    git clone https://github.com/cockpit-project/cockpit
fi

if [ ! -f $TMPDIR/vm-prep-was-run ]; then
    sudo /usr/local/bin/vm-prep
    touch $TMPDIR/vm-prep-was-run
fi

if [ ! -d cockpit/node_modules ]; then
    ( cd cockpit && npm install )
fi

mkdir -p mock

# If interactive arguments then just exec
if [ $loop != "yes" ]; then
    cd cockpit/
    exec "$@"
fi

echo "Starting testing"

iteration=0
while true; do
    fail=0
    find cockpit -name '*.py?' -delete
    git -C cockpit fetch origin
    git -C cockpit reset --hard origin/master
    if [ "$iteration" -eq 0 ]; then
        cockpit/test/vm-download --prune
    else
        cockpit/test/vm-download
    fi
    iteration=$(( (iteration+1) % 25 ))
    if ! cockpit/test/github-task "$@"; then
        exit
    fi
done
