# update existing instance:
# ansible -v -i inventory -m include_role -a name=webhook  tag_Name_cockpit_webhook
---
- name: Upload RabbitMQ k8s resource
  copy:
    src: "{{ role_path }}/../../../tasks/cockpit-tasks-webhook.yaml"
    dest: /run/cockpit-tasks-webhook.yaml
    mode: preserve

# keep this in sync with test/test_deployment.py
- name: Generate flat files from RabbitMQ config map
  shell: |
    rm -rf /etc/rabbitmq
    mkdir -p /etc/rabbitmq
    python3 - <<EOF
    import os.path
    import yaml
    with open("/run/cockpit-tasks-webhook.yaml") as f:
        for doc in yaml.full_load_all(f):
            if doc["metadata"]["name"] == "amqp-config":
                break
    files = doc["data"]
    for name, contents in files.items():
        with open(os.path.join('/etc/rabbitmq', name), 'w') as f:
            f.write(contents)
    EOF

- name: Install pod systemd unit
  copy:
    src: "{{ role_path }}/cockpituous-webhook.service"
    dest: /etc/systemd/system/cockpituous-webhook.service
    mode: preserve

- name: reload systemd
  command: systemctl daemon-reload

- name: Start pod
  service:
    name: cockpituous-webhook.service
    state: restarted
    enabled: yes
