- name: Create s3-keys alias
  file:
    src: self-hosted
    dest: "/var/lib/cockpit-secrets/s3-keys/{{ hostvars[groups['psi_s3'][0]].ansible_host }}"
    state: link
    owner: cockpituous
    group: cockpituous
