---
plugin: aws_ec2
regions:
  - us-east-1
keyed_groups:
  - prefix: tag
    key: tags
# needed to avoid trying to talk to *.ec2.internal DNS names
hostnames:
  - dns-name
  - private-ip-address
filters:
  tag:ServiceOwner: FrontDoorSST
compose:
  ansible_become: true
