#!/bin/sh
# Run this in a home directory with all credentials; write OpenShift secret
# volumes YAML definitions to stdout
# https://docs.openshift.com/container-platform/3.9/dev_guide/secrets.html

set -eu

TOKEN=${1:-$HOME/.config/github-token}

cat <<EOF
---
apiVersion: v1
kind: List
items:
- kind: Secret
  apiVersion: v1
  metadata:
    name: learn-tests-secrets
  data:
EOF

printf '    github-token: %s\n' "$(base64 --wrap=0 $TOKEN)"
