---
apiVersion: v1
kind: List
items:
- kind: Route
  apiVersion: v1
  metadata:
    name: cockpit-expose
  spec:
    to:
      kind: Service
      name: cockpit-learn
    port:
      targetPort: 8080
