---
apiVersion: v1
kind: List
items:
- kind: Pod
  apiVersion: v1
  metadata:
    name: cockpit-learn
    labels:
      infra: cockpit-learn
  spec:
    containers:
      - name: predict
        image: docker.io/cockpit/learn
        command: [ "/learn/predict-server" ]
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
        volumeMounts:
         - name: cache
           mountPath: /cache
         - name: train
           mountPath: /cache/train
         - name: secrets
           mountPath: /secrets
           readOnly: true
      - name: train
        image: docker.io/cockpit/learn
        command: [ "/learn/train-tests", "--verbose", "--batch", "/cache/train/*" ]
        volumeMounts:
         - name: cache
           mountPath: /cache
         - name: train
           mountPath: /cache/train
    volumes:
    - name: cache
      emptyDir: { }
    - name: train
      emptyDir: { }
    - name: secrets
      secret:
        secretName: cockpit-tasks-secrets
    restartPolicy: Never
- kind: Service
  apiVersion: v1
  metadata:
    name: cockpit-learn
  spec:
    selector:
      infra: cockpit-learn
    ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
- kind: Route
  apiVersion: v1
  metadata:
    name: learn
  spec:
    to:
      kind: Service
      name: cockpit-learn
    port:
      targetPort: 8443
    tls:
      termination: passthrough
