---
apiVersion: v1
kind: List
items:
- kind: Pod
  apiVersion: v1
  metadata:
    name: learn-tests-v2
    labels:
      infra: learn-tests-v2
  spec:
    containers:
      - name: predict
        image: docker.io/cockpit/learn:v2
        command: [ "lighttpd", "-D", "-f", "/learn/lighttpd.conf" ]
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8090
            protocol: TCP
        volumeMounts:
         - name: cache
           mountPath: /cache
         - name: train
           mountPath: /cache/train
      - name: train
        image: docker.io/cockpit/learn:v2
        command: [ "/learn/train-tests", "--verbose", "--batch", "/cache/train/*" ]
        volumeMounts:
         - name: cache
           mountPath: /cache
         - name: train
           mountPath: /cache/train
    volumes:
    - name: cache
      emptyDir: { }
    - name: train
      emptyDir: { }
- kind: Service
  apiVersion: v1
  metadata:
    name: learn-tests-v2
  spec:
    selector:
      infra: learn-tests-v2
    ports:
    - name: http
      port: 80
      targetPort: 8090
      protocol: TCP
