---
apiVersion: v1
kind: List
items:
- kind: Route
  apiVersion: v1
  metadata:
    name: learn-tests
  spec:
    to:
      kind: Service
      name: learn-tests
    port:
      targetPort: 8080
- kind: Service
  apiVersion: v1
  metadata:
    name: learn-tests
  spec:
    selector:
      infra: learn-tests-v2
    ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
