---
- name: Create demo instance
  hosts: localhost
  gather_facts: false
  vars_files: aws_defaults.yml

  tasks:
    - import_tasks: tasks/launch-rhel8.yml
      vars:
        tag_name: cockpit-demo
        tag_service_component: Demo
        # public internet
        vpc_subnet_id: subnet-988c7ed5
        network:
          assign_public_ip: yes

- name: Configure instances
  hosts: launched
  become: true
  gather_facts: true
  roles:
    - cockpit-copr
    - cockpit-demo-generic
