---
- name: Create public webhook EC2 instance
  hosts: localhost
  gather_facts: false
  vars_files: aws_defaults.yml

  tasks:
    - import_tasks: tasks/launch-coreos.yml
      vars:
        tag_name: cockpit-webhook
        tag_service_component: Webhook
        # persistent network device with stable external IP 3.228.126.27
        network:
          interfaces:
            - eni-004f5b4f714f3fda9
        volumes:
          # default 10 GB are not enough for two rpm-ostree deployments and tasks container
          - device_name: /dev/xvda
            ebs:
              volume_size: 20
              delete_on_termination: true

- name: Configure instances
  hosts: launched
  vars_files: aws_defaults.yml
  gather_facts: true
  roles:
    - role: users
      vars:
        user: "{{ aws_coreos_defaultuser }}"
    - install-secrets-dir
    - webhook

  tasks:
    - name: Set host name
      hostname:
        name: aws-webhook
