#!/bin/sh

set -eux

COCKPIT_BOTS_REPO=${COCKPIT_BOTS_REPO:-https://github.com/cockpit-project/bots}
COCKPIT_BOTS_BRANCH=${COCKPIT_BOTS_BRANCH:-main}

# let's just do our work in the current directory
WORKDIR="$PWD"
BOTS_DIR="$WORKDIR"/bots

echo "Starting testing"

update_bots() {
    if [ -d "$BOTS_DIR" ]; then
        git -C "$BOTS_DIR" pull --rebase
    else
        git clone --quiet -b "$COCKPIT_BOTS_BRANCH" "$COCKPIT_BOTS_REPO" "$BOTS_DIR"
    fi
}

# Listen to SIGTERM for orderly shutdown
shutdown=
trap "echo 'received SIGTERM, stopping main loop'; shutdown=1" TERM

# Run for ~ 12 hours, so that we regularly pick up new tasks image updates
start_time=$(date +%s)
end_time=$((start_time + 43200))  # 12 hours = 43200 seconds

while [ "$(date +%s)" -lt "$end_time" ]; do
    [ -z "$shutdown" ] || break
    update_bots
    cd "$BOTS_DIR"

    # run-queue fails on empty queues; don't poll too often
    timeout 12h ./run-queue ${AMQP_SERVER:+--amqp} ${AMQP_SERVER:-} || sleep 10
done

# Prune old images on our local cache (not needed for statistics queue)
if [ -z "${RUN_STATISTICS_QUEUE:-}" ]; then
    update_bots
    ./image-prune
fi
