#!/bin/sh

set -eux

COCKPIT_BOTS_REPO=${COCKPIT_BOTS_REPO:-https://github.com/cockpit-project/bots}
COCKPIT_BOTS_BRANCH=${COCKPIT_BOTS_BRANCH:-main}

# let's just do our work in the current directory
WORKDIR="$PWD"
BOTS_DIR="$WORKDIR"/bots

echo "Starting testing"

function update_bots() {
    if [ -d "$BOTS_DIR" ]; then
        git -C "$BOTS_DIR" pull --rebase
    else
        git clone --quiet -b "$COCKPIT_BOTS_BRANCH" "$COCKPIT_BOTS_REPO" "$BOTS_DIR"
    fi
}

# wait between 1 and 10 minutes, with an override to speed up tests
function slumber() {
    if [ -n "${SLUMBER:-}" ]; then
        sleep "$SLUMBER"
    else
        sleep $(shuf -i ${1:-60-600} -n 1)
    fi
}

# on mass deployment, avoid GitHub stampede
slumber 0-120

# Consume from queue 30 times, then restart; listen to SIGTERM for orderly shutdown
shutdown=
trap "echo 'received SIGTERM, stopping main loop'; shutdown=1" TERM

for i in $(seq 1 30); do
    [ -z "$shutdown" ] || break
    update_bots
    cd "$BOTS_DIR"

    # run-queue fails on empty queues; don't poll too often
    timeout 12h ./run-queue ${AMQP_SERVER:+--amqp} ${AMQP_SERVER:-} || slumber
done

# Prune old images on our local cache
update_bots
./image-prune
