#!/usr/bin/python3

import contextlib
import http.server
import json
import logging
import os
import ssl
import subprocess
import sys
import time

import pika

import github_handler

# Reduce pika noise
logging.getLogger("pika").propagate = False

HOME_DIR = '/tmp/home'
WEBHOOK_SECRETS = '/run/secrets/webhook'
AMQP_SERVER = None  # initialized in setup()
COCKPIT_BOTS_REPO = os.getenv('COCKPIT_BOTS_REPO', 'https://github.com/cockpit-project/bots')
COCKPIT_BOTS_BRANCH = os.getenv('COCKPIT_BOTS_BRANCH', 'main')
BOTS_CHECKOUT = HOME_DIR + '/bots'
sys.path.append(BOTS_CHECKOUT)

PASSWD_ENTRY_SCRIPT = '''
set -ex
if ! whoami && [ -w /etc/passwd ]; then
    echo "user:x:$(id -u):0:random uid:${HOME:-/home/user}:/sbin/nologin" >> /etc/passwd
fi
'''


def setup_home():
    """Prepare temporary home directory from secrets"""

    if os.path.isdir(HOME_DIR):
        return
    logging.debug('Initializing %s', HOME_DIR)
    os.makedirs(HOME_DIR)


def ensure_bots_checkout():
    if not os.path.isdir(BOTS_CHECKOUT):
        subprocess.check_call(['git', 'clone', COCKPIT_BOTS_REPO, BOTS_CHECKOUT])
    subprocess.check_call(['git', '-C', BOTS_CHECKOUT, 'fetch', 'origin'])
    subprocess.check_call(['git', '-C', BOTS_CHECKOUT, 'reset', '--hard'])
    subprocess.check_call(['git', '-C', BOTS_CHECKOUT, 'clean', '-dxff'])
    subprocess.check_call(['git', '-C', BOTS_CHECKOUT, 'checkout', 'origin/' + COCKPIT_BOTS_BRANCH])


@contextlib.contextmanager
def distributed_queue(amqp_server):
    try:
        host, port = amqp_server.split(':')
    except ValueError:
        logging.error('Please format amqp_server as host:port')
        sys.exit(1)

    context = ssl.create_default_context(cafile=f'{WEBHOOK_SECRETS}/ca.pem')
    context.load_cert_chain(keyfile=f'{WEBHOOK_SECRETS}/amqp-client.key',
                            certfile=f'{WEBHOOK_SECRETS}/amqp-client.pem')
    context.check_hostname = False
    connection = pika.BlockingConnection(pika.ConnectionParameters(
        host=host,
        port=int(port),
        ssl_options=pika.SSLOptions(context, server_hostname=host),
        credentials=pika.credentials.ExternalCredentials()))
    channel = connection.channel()

    channel.queue_declare(queue='webhook', auto_delete=False)
    yield channel
    connection.close()


def scan_tasks():
    """scan project PRs and issues to (re)build the tasks queue"""

    from lib import testmap
    from task.distributed_queue import DEFAULT_AMQP_SERVER
    global AMQP_SERVER
    AMQP_SERVER = os.getenv('AMQP_SERVER', DEFAULT_AMQP_SERVER)

    # wait a bit for AMQP server to start up, on the infra it is started together with webhook
    for retry in range(10):
        try:
            with distributed_queue(AMQP_SERVER):
                break
        except (OSError, pika.exceptions.AMQPError) as e:
            logging.info("Failed to connect to AMQP, attempt #%i: %s", retry, e)
            time.sleep(5)

    for project in testmap.projects():
        subprocess.check_call([os.path.join(BOTS_CHECKOUT, 'tests-scan'), '--amqp',
                               AMQP_SERVER, '--repo', project],
                              cwd=BOTS_CHECKOUT)
        subprocess.check_call([os.path.join(BOTS_CHECKOUT, 'issue-scan'), '--amqp',
                               AMQP_SERVER, '--repo', project],
                              cwd=BOTS_CHECKOUT)


def publish_to_queue(routing_key, event, request):
    body = {
        'event': event,
        'request': request,
    }
    with distributed_queue(AMQP_SERVER) as queue:
        queue.basic_publish('', routing_key, json.dumps(body),
                            properties=pika.BasicProperties(content_type='application/json'))


class CockpituousHandler(github_handler.GithubHandler):
    def handle_event(self, event, request):
        logging.info('Handling %s event', event)
        if event == 'pull_request':
            return self.handle_pull_request_event(event, request)
        elif event == 'status':
            return self.handle_status_event(event, request)
        elif event == 'issues':
            return self.handle_issues_event(event, request)
        return (501, 'unsupported event ' + event)

    def handle_pull_request_event(self, event, request):
        repo = request['pull_request']['base']['repo']['full_name']
        title = request['pull_request']['title']
        number = int(request['number'])
        action = request['action']
        merged = request['pull_request'].get('merged', False)

        logging.info('repo: %s; title: %s; number: %d; action: %s', repo, title, number, action)
        # see https://developer.github.com/v3/activity/events/types/#pullrequestevent for all actions
        if action == 'closed' and merged:
            logging.info("pull request was merged, ensuring cockpit checkout is latest main")
            ensure_bots_checkout()
        elif action not in ['opened', 'synchronize', 'edited', 'labeled']:
            logging.info("action %s unknown, skipping pull request event", action)
            return None

        publish_to_queue('webhook', event, request)
        return None

    def handle_status_event(self, event, request):
        repo = request['repository']['full_name']
        sha = request['sha']
        state = request['state']
        description = request.get('description', '')
        if state != 'pending':
            return None
        # only allow manually triggered tests
        logging.info('repo: %s; sha: %s; state: %s; description: %s', repo, sha, state, description)
        if not description.rstrip().endswith('(direct trigger)'):
            logging.info("Status description doesn't end with '(direct trigger)', skipping testing")
            return None

        publish_to_queue('webhook', event, request)
        return None

    def handle_issues_event(self, event, request):
        action = request['action']
        if event == 'issues' and action not in ['edited', 'labeled']:
            logging.info("action %s unknown, skipping issues event", action)
            return None

        publish_to_queue('webhook', event, request)
        return None

    def do_GET(self):
        if self.path == '/inspect-queue':
            self.wfile.write(b'HTTP/1.1 200\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n')
            try:
                subprocess.check_call([f'{BOTS_CHECKOUT}/inspect-queue'], stdout=self.wfile)
            except (subprocess.CalledProcessError, FileNotFoundError) as e:
                self.wfile.write(b'Failed: ' + bytes(str(e), 'utf-8'))
        else:
            self.wfile.write(b'HTTP/1.1 404\r\n\r\nNot found')


#
# main
#

logging.basicConfig(level=logging.DEBUG)  # INFO

# ensure we have a passwd entry for random UIDs
# https://docs.openshift.com/container-platform/3.7/creating_images/guidelines.html
subprocess.check_call(PASSWD_ENTRY_SCRIPT, shell=True)

os.environ['HOME'] = HOME_DIR

setup_home()
ensure_bots_checkout()
scan_tasks()

http.server.HTTPServer(('', 8080), CockpituousHandler).serve_forever()
