---
 - name: Upload secrets
   copy:
     src: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}/ci-secrets.tar.gz"
     dest: /tmp/secrets.tar.gz
     mode: '0600'

 - name: Clean up old secrets directory
   file:
     path: /var/lib/cockpit-secrets
     state: absent

 - name: Set up secrets dir
   file:
     path: /var/lib/cockpit-secrets
     owner: cockpituous
     group: cockpituous
     state: directory
     setype: container_file_t

 - name: Unarchive secrets
   unarchive:
     src: /tmp/secrets.tar.gz
     remote_src: true
     dest: /var/lib/cockpit-secrets/
     owner: cockpituous
     group: cockpituous
     mode: 'u=rwX,g=rX,o=rX'
     setype: container_file_t

 - name: Clean up secrets archive
   file:
     path: /tmp/secrets.tar.gz
     state: absent

 # the above empties the /secrets volume for running containers
 - name: Restart webhook and image containers to pick up changed secrets
   # The glob avoids failure on machines which are not running webhook
   command: systemctl restart cockpituous-webhook*.service

 - name: Restart systemd controlled tasks containers to pick up changed secrets
   command: systemctl restart cockpit-tasks@*
