#! /usr/bin/env python
#
# Example program using irclib.py.
#
# This program is free without restrictions; do anything you like with
# it.
#
# Joel Rosdahl <joel@rosdahl.net>

server = "localhost"
port = 6667
target = "#cockpit"
nickname = "cockpituous"
password = "cockpituous:foobar:freenode"
ssl=True

import irclib
import sys

def on_connect(connection, event):
    if irclib.is_channel(target):
        connection.join(target)
    else:
        while 1:
            line = sys.stdin.readline()
            if not line:
                break
            connection.privmsg(target, line)
        connection.quit("Using irclib.py")

def on_join(connection, event):
    while 1:
        line = sys.stdin.readline()
        if not line:
            break
        connection.privmsg(target, line)
    connection.quit("Using irclib.py")

def on_disconnect(connection, event):
    sys.exit(0)

irc = irclib.IRC()
try:
    c = irc.server().connect(server, port, nickname, password=password, ssl=ssl)
except irclib.ServerConnectionError, x:
    print x
    sys.exit(1)

c.add_global_handler("welcome", on_connect)
c.add_global_handler("join", on_join)
c.add_global_handler("disconnect", on_disconnect)

irc.process_forever()
