---
apiVersion: v1
kind: List
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    name: sink
  spec:
    replicas: 1
    selector:
      infra: sink
    template:
      metadata:
        name: sink
        labels:
          infra: sink
      spec:
        containers:
          - name: sink
            image: cockpit/images
            ports:
              - containerPort: 8080
                protocol: TCP
                name: http
              - containerPort: 8022
                protocol: TCP
                name: ssh
            command: [ 'sh', '-ec', 'OUT=$(sed "/^user:/d; /^$(id -u):/d" /etc/passwd); echo -e "$OUT\nuser:x:$(id -u):0:user:/home/user:/bin/bash" > /etc/passwd; /usr/sbin/sshd -p 8022 -o StrictModes=no -E /dev/stderr; /usr/sbin/nginx -g "daemon off;"' ]
            volumeMounts:
            - name: images
              mountPath: /cache/images
            - name: webhook-secrets
              mountPath: /run/secrets/webhook
              readOnly: true
            - name: task-secrets
              mountPath: /secrets
              readOnly: true
            - name: config
              mountPath: /run/config
              readOnly: true
        volumes:
        - name: images
          persistentVolumeClaim:
            claimName: cockpit-images
        - name: webhook-secrets
          secret:
            secretName: webhook-secrets
        - name: task-secrets
          secret:
            secretName: cockpit-tasks-secrets
        - name: config
          configMap:
            name: sink-config

- kind: Service
  apiVersion: v1
  metadata:
    name: sink-http
  spec:
    clusterIP: None
    selector:
      infra: sink
    ports:
    # we use edge termination, so talk to plain http
    - targetPort: http
      port: 443
      protocol: TCP
      name: http

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: logs-https
  spec:
    to:
      kind: Service
      name: sink-http
    port:
      targetPort: http
    tls:
      termination: edge

- kind: Service
  apiVersion: v1
  metadata:
    name: sink-ssh
  spec:
    clusterIP: None
    selector:
      infra: sink
    ports:
    - targetPort: 8022
      port: 8022
      protocol: TCP
      name: ssh

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: sink-config
  data:
    sink: |
        [Sink]
        Url: https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/%(identifier)s/
        Logs: /cache/images/logs
        PruneInterval: 14
