# This is a clouds.yaml file, which can be used by OpenStack tools as a source
# of configuration on how to connect to a cloud. If this is your only cloud,
# just put or symlink this file in ~/.config/openstack/clouds.yaml and tools like
# python-openstackclient will just work with no further config.
#
# If you have more than one cloud account, add the cloud entry to the clouds
# section of your existing file and you can refer to them by name with
# OS_CLOUD=openstack or --os-cloud=openstack
#
# Go to Overview → Identity → Application Credentials → Create Application Credential
# and generate a credential. Create ~/.config/openstack/secure.yaml with the template
# below, add the generated credential to it, and set tight (0600) permissions:
#
# clouds:
#   rhos-01:
#     application_credential_id: "..."
#     application_credential_secret: "..."
clouds:
  rhos-01:
    auth:
      auth_url: https://api.rhos-01.prod.psi.rdu2.redhat.com:13000
    region_name: "regionOne"
    interface: "public"
    identity_api_version: 3
    auth_type: "v3applicationcredential"
  rhos-d:
    auth:
      auth_url: https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000
    region_name: "regionOne"
    interface: "public"
    identity_api_version: 3
