---
- name: Set up S3 image cache
  hosts: psi_s3
  gather_facts: false
  roles:
    - role: s3-systemd
      vars:
        # we have no stable IP and no DNS, and subjectAltNames don't support IP patterns
        disable_tls: 1
    - role: local-s3-alias

- name: Configure image cache on all task runners
  hosts: openstack_tasks
  gather_facts: false
  tasks:
    - name: Create config file with store URL
      copy:
        dest: /var/cache/cockpit-tasks/image-stores
        mode: 0644
        content: |
          http://{{ hostvars[groups["psi_s3"][0]].ansible_host }}/images/

    - name: Tell tasks containers to drain and restart
      command: pkill -ex cockpit-tasks
