---
- name: Create tasks runner OpenStack instance
  hosts: localhost
  gather_facts: false
  vars_files: psi_defaults.yml
  roles:
    - role: launch-openstack-instance
      vars:
        # playbook can be called with `-e instance_name=..` to use a different name
        instance_name: '{{ psi_cloud }}-1'
        ssh_user: '{{ psi_user }}'
        cloud: '{{ psi_cloud }}'
        image: '{{ psi_image }}'
        flavor: '{{ psi_flavor }}'
        network: '{{ psi_network }}'
        os_group: "openstack_tasks"

- name: Early setup
  gather_facts: false
  hosts: launched
  vars_files: psi_defaults.yml
  tasks:
    - name: Install Python for Ansible
      raw: type python3 || rpm-ostree install -y --apply-live python3 python3-libselinux python3-pyyaml

    - name: Set host name
      hostname:
        name: "{{ instance_name | default('{{ psi_cloud }}-1') }}"

- name: Configure instances
  hosts: launched
  vars_files: psi_defaults.yml
  roles:
    - role: users
      vars:
        user: "{{ psi_user }}"
    - chrony-redhat
    - ci-data-cache
    - install-secrets-dir
    - role: tasks-systemd
      vars:
        instances: 1
