---
apiVersion: v1
kind: List
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    name: images
  spec:
    replicas: 1
    selector:
      infra: cockpit-images
    template:
      metadata:
        labels:
          infra: cockpit-images
      spec:
        containers:
          - name: images
            image: cockpit/images
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
            volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
            - name: images
              mountPath: /cache/images
            - name: httpd-log
              mountPath: /var/log/nginx
            - name: httpd-state
              mountPath: /var/lib/nginx
            - name: httpd-state-tmp
              mountPath: /var/lib/nginx/tmp
        volumes:
        - name: images
          persistentVolumeClaim:
            claimName: cockpit-images
        - name: secrets
          secret:
            secretName: cockpit-tasks-secrets
        - name: httpd-log
          emptyDir:
            medium: Memory
        - name: httpd-state
          emptyDir:
            medium: Memory
        - name: httpd-state-tmp
          emptyDir:
            medium: Memory

- kind: Service
  apiVersion: v1
  metadata:
    name: cockpit-images
  spec:
    clusterIP: None
    selector:
      infra: cockpit-images
    ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP

- kind: Route
  apiVersion: v1
  metadata:
    name: images
  spec:
    to:
      kind: Service
      name: cockpit-images
    port:
      targetPort: 8443
    tls:
      termination: passthrough
