#!/bin/sh

set -eufx

CACHE=/var/cache/cockpit-tasks
SECRETS=/var/lib/cockpit-secrets/tasks

if RUNC=$(which podman 2>/dev/null); then
    UNIT_DEPS=''
else
    RUNC=$(which docker)
    UNIT_DEPS="Requires=docker.service
After=docker.service"
fi

mkdir -p $SECRETS $CACHE/images
chown -R 1111:1111 $SECRETS $CACHE
chcon -R -t container_file_t $SECRETS $CACHE

cat <<EOF > /etc/systemd/system/cockpit-images.service
[Unit]
Description=Cockpit Images
$UNIT_DEPS

[Service]
Environment="TASK_CACHE=$CACHE"
Environment="TASK_SECRETS=$SECRETS"
Restart=always
RestartSec=60
ExecStartPre=-$RUNC rm -f cockpit-images
ExecStart=/bin/sh -xc "$RUNC run --name=cockpit-images --publish=8090:8080 --publish=8493:8443 --volume=\$TASK_SECRETS:/secrets:ro --volume=\$TASK_CACHE/images:/cache/images:rw cockpit/images"
ExecStop=$RUNC rm -f cockpit-images

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
