#!/bin/sh

set -eufx

CACHE=/var/cache/cockpit-tasks
SECRETS=/var/lib/cockpit-secrets/tasks

mkdir -p $CACHE $SECRETS
chown -R 1111:1111 $CACHE $SECRETS

cat <<EOF > /etc/systemd/system/cockpit-images.service
[Unit]
Description=Cockpit Images
Requires=docker.service
After=docker.service

[Service]
Environment="TASK_CACHE=$CACHE"
Environment="TASK_SECRETS=$SECRETS"
Restart=always
RestartSec=60
ExecStartPre=-/usr/bin/docker rm -f cockpit-images
ExecStart=/bin/sh -xc "/usr/bin/docker run --name=cockpit-images --publish=8090:8080 --publish=8493:8443 --volume=\$TASK_SECRETS:/secrets:ro --volume=\$TASK_CACHE:/cache:rw cockpit/images"
ExecStop=/usr/bin/docker rm -f cockpit-images

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
