{
 "title": "Cockpit CI",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cockpit_project",
    "label": "GitHub project name",
    "query": {
     "query": "label_values(top_failures_pct, project)"
    }
   },
   {
    "name": "coverage_project",
    "label": "GitHub project name",
    "query": {
     "query": "label_values(test_coverage, project)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SLI: % tests with queue time > 5 min",
   "type": "graph",
   "description": "SLO: 95% of test runs spend no more than 5 minutes in the queue until they get assigned to a runner.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "1 - sum(rate(queue_time_wait_seconds_bucket{le=\"300\"}[$__range])) / sum(rate(queue_time_wait_seconds_count[$__range]))"
    }
   ]
  },
  {
   "title": "#queued tests in last 24h",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(queue_time_wait_seconds_count[24h]) * 86400"
    }
   ]
  },
  {
   "title": "SLI: #tests which fail > 10% of the time",
   "type": "graph",
   "description": "SLO: Every individual test succeeds at least 90% of the time ; i.e. this must be zero for normal operations",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "count(top_failures_pct)" }
   ]
  },
  {
   "title": "Top slowest tests",
   "type": "bargauge",
   "description": "The top 10 slowest tests per project",
   "gridPos": { "h": 22, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "top_slowest_tests", "legendFormat": "{{ test }}" }
   ]
  },
  {
   "title": "$cockpit_project unstable tests",
   "type": "bargauge",
   "description": "$cockpit_project tests which fail in more than 10% of runs (SLO: 0)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "repeat": "cockpit_project",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "top_failures_pct{project=\"$cockpit_project\"}"
    }
   ]
  },
  {
   "title": "SLI: % tests with run time > 1h",
   "type": "graph",
   "description": "SLO: 95% of test runs take no more than 1 hour to execute.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "1 - sum(rate(test_run_seconds_bucket{le=\"3600\"}[$__range])) / sum(rate(test_run_seconds_count[$__range]))"
    }
   ]
  },
  {
   "title": "Avg queue time in last 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(queue_time_wait_seconds_sum[$__range])) / sum(rate(queue_time_wait_seconds_count[$__range]))"
    }
   ]
  },
  {
   "title": "Avg test run time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(test_run_seconds_sum[$__range])) / sum(rate(test_run_seconds_count[$__range]))"
    }
   ]
  },
  {
   "title": "SLI: Merged PRs without retries",
   "type": "graph",
   "description": "SLO: A merged PR became fully green with a 75% chance at the first attempt",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pr_retries_bucket{le=\"0\"}[$__range])) / sum(rate(pr_retries_count[$__range]))"
    }
   ]
  },
  {
   "title": "SLI: Merged PRs with >= 2 retries",
   "type": "graph",
   "description": "SLO: A merged PR became fully green with a 95% chance at the second attempt, so this ought to be < 5%",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(rate(pr_retries_bucket{le=\"1\"}[$__range])) / sum(rate(pr_retries_count[$__range]))"
    }
   ]
  },
  {
   "title": "SLI: Merged PRs with failures",
   "type": "graph",
   "description": "SLO: 95% of PRs get merged with successful tests",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(merged_failures[$__range])/rate(pr_retries_sum[$__range])"
    }
   ]
  },
  {
   "title": "$coverage_project code coverage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "repeat": "coverage_project",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "test_coverage{project=\"$coverage_project\"}"
    }
   ]
  },
  {
   "title": "used S3 space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(s3_usage_bytes)" }
   ]
  }
 ]
}