#!/bin/sh
# Run this in a home directory with all credentials; write OpenShift secret
# volumes YAML definitions to stdout
# https://docs.openshift.com/container-platform/3.9/dev_guide/secrets.html
set -eu

cat <<EOF
---
apiVersion: v1
kind: List
items:
EOF

# release secrets
cat <<EOF
- apiVersion: v1
  kind: Secret
  metadata:
    name: cockpit-release-secrets
  data:
EOF
for f in $(find .ssh .gnupg .config .pki .fedora* .gitconfig -type f ! -name github-webhook-token); do
    printf '    %s: %s\n' "$(echo $f | sed "s!/!--!g")" "$(base64 --wrap=0 $f)"
done
