#!/bin/sh
# Run this in a home directory with all credentials; write OpenShift secrets
# volume JSON definition to stdout
# https://docs.openshift.com/container-platform/3.9/dev_guide/secrets.html
set -eu

printf '{ "apiVersion": "v1", "kind": "Secret", "metadata": { "name": "cockpit-release-secrets" }, "data": {\n'

first=yes
cd ~
for f in $(find .ssh .gnupg .config .pki .fedora* .gitconfig -type f); do
    [ -n "$first" ] || printf ',\n'
    printf '\t"%s": "%s"' "$(echo $f | sed "s!/!--!g")" "$(base64 --wrap=0 $f)"
    first=''
done
printf '\n} }\n'
