#!/bin/sh

set -ex


if [ ! -d cockpit ]; then
    git clone https://github.com/cockpit-project/cockpit
fi

if [ ! -d cockpit/node_modules ]; then
    ( cd cockpit/ && npm install )
fi

echo "Starting release"
cd cockpit && release-runner /usr/local/bin/cockpit-script
