#!/bin/sh

# This is certified, A-grade, high quality turd polish. Node leaves
# stdio file descriptors in non-blocking mode when exiting. This has
# been reported, fixed, unfixed, ad nauseum.
#
# https://github.com/nodejs/node/issues/14752
# https://github.com/nodejs/node/pull/17737
# https://github.com/nodejs/node/pull/20592
# https://github.com/nodejs/node/pull/21257
#
# It's starting to fester.

OUT=$(/usr/bin/node.real "$@" 2>&1 </dev/null)
ret=$?
echo -n "$OUT"
exit $ret
