#!/bin/sh -euf
#
# release-bodhi
#
# A script that does a Bodhi update request.
#
# Arguments are described here. Most arguments have an equivalent envvar.
#
# -p srpm    RELEASE_SRPM=srpm      Path to SRPM
# -q         RELEASE_QUIET=1        Make output more quiet
# -x         RELEASE_TRANSACTION=1  SIGSTOP before pushing the dist-git commit
# -v         RELEASE_VERBOSE=1      Make output more verbose
#

set -euf

# Various arguments
TRANSACTION=${RELEASE_TRANSACTION:-0}
QUIET=${RELEASE_QUIET:-0}
VERBOSE=${RELEASE_VERBOSE:-0}
SRPM=${RELEASE_SRPM:-$PWD/srpm}
CHECK=${RELEASE_CHECK:-0}

# Other globals
USER=""
PASSWORD=""
FEDORA=""
USER=""
NVR=""

usage()
{
    echo "usage: release-bodhi [-qvxz] [-p SRPM] FEDORA" >&2
    exit ${1-2}
}

trace()
{
    if [ $QUIET -eq 0 ]; then
        echo "> $@" >&2
    fi
}

message()
{
    echo "release-bodhi: $@" >&2
}

check()
{
    USER="$(cat ~/.config/bodhi-user)"
    if [ -z "$USER" ]; then
        message "no valid ~/.config/bodhi-user found"
        exit 2
    fi

    PASSWORD="$(cat ~/.config/bodhi-password)"
    if [ -z "$PASSWORD" ]; then
        message "no valid ~/.config/bodhi-password found"
        exit 2
    fi
}

prepare()
{
    NVR="$(rpm --qf '%{Name}-%{Version}-%{Release}\n' -qp $SRPM)"
    if [ -z "$NVR" ]; then
        message "$SRPM: is not a valid source rpm"
        exit 1
    fi
    NOTES="$(rpm --changelog -qp $SRPM | sed -n '2,/^$/p')"
    if [ -z "NOTES" ]; then
        message "$SRPM: doesn't have a valid changelog"
        exit 1
    fi
}

commit()
(
    # Ignore bodhi failures until Fedora bodhi infrastructure stops being so broken
    set +e
echo "$PASSWORD" | setsid -w -- bodhi --new --type=enhancement --close-bugs --notes="$NOTES" \
        --stablekarma=2 --unstablekarma=-1 --request=stable --release="$FEDORA" \
        --username=$USER "$NVR"
    set -e
)

while getopts "p:qvxz" opt; do
    case "$opt" in
    p)
        SRPM="$OPTARG"
        ;;
    q)
        QUIET=1
        VERBOSE=0
        ;;
    v)
        QUIET=0
        VERBOSE=1
        ;;
    x)
        TRANSACTION=1
        ;;
    z)
        CHECK=1
        ;;
    -)
        break
        ;;
    *)
        usage
        ;;
    esac
done

shift $(expr $OPTIND - 1)

check

if [ $CHECK -eq 1 ]; then
    exit 0
fi

if [ $# -ne 1 ]; then
    usage
fi

FEDORA="$1"

if [ -z "$SRPM" ]; then
    message "no package specified"
    exit 2
fi

prepare

if [ $TRANSACTION -eq 1 ]; then
    kill -STOP $$
fi

commit
