#!/bin/sh -euf
#
# release-runner
#
# Runs a delivery script.
#
# The script is a shell script. Items in the script can be preceeded
# with the word 'job'. If so, they will get $RELEASE_XXX envars exported
# and asked to run transactionally.
#
# If a given script item can run transactionally, it will pause before
# making published, permanent changes ... and wait for all the other
# jobs to proceed. If all succeed, then they are all unpaused and
# allowed to continue to completion, one at a time.
#
# Arguments are described here. Most arguments have an equivalent envvar.
#
# -n                                Dry run, stop before publishing changes
# -q         RELEASE_QUIET=1        Make output more quiet
# -v         RELEASE_VERBOSE=1      Make output more verbose
# -z         RELEASE_CHECK=1        Check access and configuration
# -l         RELEASE_SINK=1         Host to sink logs to
# -t         RELEASE_TAG=0.X        Tag to release
#


set -euf

# We want job control
set -m

SINK=${RELEASE_SINK:-}
RELEASE_TAG=${RELEASE_TAG:-}
FAIL=0
DRYRUN=0
JOBS=""

usage()
{
    echo "usage: release-runner [-nqvz] [-t TAG] SCRIPT" >&2
    exit ${1:-2}
}

trace()
{
    if [ ${RELEASE_QUIET:-0} -eq 0 ]; then
        echo "> $@" >&2
    fi
}

message()
{
    echo "release-runner: $@" >&2
}

job()
{
    local ret

    RELEASE_TARBALL=${RELEASE_TARBALL:-$PWD/tarball}
    RELEASE_SRPM=${RELEASE_SRPM:-$PWD/srpm}
    RELEASE_DEBIAN_REPO=${RELEASE_DEBIAN_REPO:-$PWD/debian-apt}
    RELEASE_TRANSACTION=1

    # Export all RELEASE_XXXX variables
    eval $(set | sed -n 's/^\(RELEASE_[^=]\+\)=.*/export \1/p')

    if [ ${RELEASE_CHECK:-0} -eq 1 ]; then
        trace "Checking: $@"
    else
        trace "Starting: $@"
    fi

    # Run the task
    set +e
    "$@"
    ret=$?
    set -e

    if [ $ret -eq 0 ]; then
        trace "Done: $@"
        return 0 # completed successfully

    elif [ $ret -gt 128 -a $ret -lt 193 ]; then
        sig=$(kill -l $ret)
        if [ "$sig" = "STOP" ]; then
            trace "Ready: $@"
            return 0 # job not yet finished
        else
            message "terminated with $sig: $@"
        fi

    elif [ ${RELEASE_CHECK:-0} -eq 1 ]; then
        trace "Fail: $@"
        FAIL=1
        return 0

    else
        message "failed code $ret: $@"
    fi

    exit $ret
}

runner()
{
    # Run the basic script
    . $1

    if [ $DRYRUN -eq 1 ]; then
        exit $FAIL
    fi

    # Run all the remaining background jobs
    JOBS=$(jobs -l | sed 's/[^0-9]*\([0-9]\+\).*/\1/')
    for job in $JOBS; do
        fg %$job
        trace "Completed job"
    done

    # Mark the build as released
    if [ -n "$RELEASE_TAG" -a -d .git ]; then
        git tag -d released-$RELEASE_TAG 2> /dev/null || true
        git tag released-$RELEASE_TAG
    fi
}

while getopts "l:nqvxz" opt; do
    case "$opt" in
    l)
        SINK="$OPTARG"
        ;;
    n)
        DRYRUN=1
        ;;
    q)
        RELEASE_QUIET=1
        RELEASE_VERBOSE=0
        ;;
    t)
        RELEASE_TAG="$OPTARG"
        ;;
    v)
        RELEASE_QUIET=0
        RELEASE_VERBOSE=1
        ;;
    z)
        RELEASE_CHECK=1
        DRYRUN=1
        ;;
    -)
        break
        ;;
    *)
        usage
        ;;
    esac
done

PATH=$PATH:$(dirname $0)

shift $(expr $OPTIND - 1)

if [ $# -ne 1 ]; then
    usage
fi

if [ -z "$RELEASE_TAG" -a -d ".git" ]; then
    git fetch origin
    RELEASE_TAG=$(git describe --match='[0-9]*' --abbrev=0 origin/master || true)
fi

if [ -z "$RELEASE_TAG" ]; then
    message "Could not find a release tag"
    exit 1
fi

if [ -d ".git" ]; then
    if git show "released-$RELEASE_TAG" -- 2> /dev/null > /dev/null; then
        exit 0
    fi
fi

if [ -z "$SINK" ]; then
    runner "$@"
else
    (
        # Respawn the current script but redirect to ssh
        export RELEASE_SINK=
        export RELEASE_TAG
        exec 2>&1
        printf '{ "message": "Release running: %s", "irc": { "channel": "#cockpit" } }\n' "$RELEASE_TAG"
        if stdbuf -oL -eL "$0" "$@"; then
            printf '\n{ "message": "Release complete: %s", "irc": { "channel": "#cockpit" } }' "$RELEASE_TAG"
        else
            printf '\n{ "message": "Release failed: %s", "irc": { "channel": "#cockpit" } }' "$RELEASE_TAG"
        fi
    ) | stdbuf -oL -eL ssh -tt "$SINK" -- python sink release-$RELEASE_TAG
fi
