#!/bin/sh -euf
#
# release-example
#
# An example release script that does nothing
#
# Arguments are described here. Most arguments have an equivalent envvar.
#
# -q         RELEASE_QUIET=1        Make output more quiet
# -x         RELEASE_TRANSACTION=1  SIGSTOP before pushing the dist-git commit
# -v         RELEASE_VERBOSE=1      Make output more verbose
# -z         RELEASE_CHECK=1        Check credentials only
#

set -euf

# Various arguments
TRANSACTION=${RELEASE_TRANSACTION:-0}
CHECK=${RELEASE_CHECK:-0}
QUIET=${RELEASE_QUIET:-0}
VERBOSE=${RELEASE_VERBOSE:-0}

usage()
{
    echo "usage: release-example [-qvxz] title" >&2
    exit ${1-2}
}

trace()
{
    if [ $QUIET -eq 0 ]; then
        echo "> $@" >&2
    fi
}

message()
{
    echo "release-example: $@" >&2
}

check()
{
    true
}

prepare()
{
    trace "Example $@"
    sleep 5
}

commit()
(
    trace "Commit $@"
    sleep 5
)

while getopts "qvxz" opt; do
    case "$opt" in
    q)
        QUIET=1
        VERBOSE=0
        ;;
    v)
        QUIET=0
        VERBOSE=1
        ;;
    x)
        TRANSACTION=1
        ;;
    z)
        CHECK=1
        ;;
    -)
        break
        ;;
    *)
        usage
        ;;
    esac
done

shift $(expr $OPTIND - 1)

if [ $# -ne 1 ]; then
    usage
fi

if [ $CHECK -eq 1 ]; then
    check "$1"
    exit 0
fi

prepare "$1"

if [ $TRANSACTION -eq 1 ]; then
    kill -STOP $$
fi

commit "$1"
