#!/bin/sh -euf
#
# release-dockerhub
#
# A script that triggers an automated build at the Docker Hub. It does
# this by updating a GitHub repository. The automated build must have
# been previously configured.
#
# We update the version number in a Dockerfile, and tests that
# the resulting URLs can be fetched. Commits the changes and pushes
# the result.
#
# Arguments are described here. Most arguments have an equivalent envvar.
#
# -p srpm    RELEASE_SRPM=srpm      Path to SRPM
# -q         RELEASE_QUIET=1        Make output more quiet
# -x         RELEASE_TRANSACTION=1  SIGSTOP before pushing the dist-git commit
# -v         RELEASE_VERBOSE=1      Make output more verbose
# -z         RELEASE_CHECK=1        Check credentials and configuration
#

set -euf

# Various arguments
TRANSACTION=${RELEASE_TRANSACTION:-0}
QUIET=${RELEASE_QUIET:-0}
VERBOSE=${RELEASE_VERBOSE:-0}
SRPM=${RELEASE_SRPM:-$PWD/srpm}
CHECK=${RELEASE_CHECK:-0}

REPO=""
SOURCE_REPO=""
WORKDIR=""
PUSH=""
CLEANUP=""

usage()
{
    echo "usage: release-dockerhub [-qvxz] [-p SRPM] [-s SOURCE_REPO ] REPO" >&2
    exit ${1-2}
}

trace()
{
    if [ $QUIET -eq 0 ]; then
        echo "> $@" >&2
    fi
}

message()
{
    echo "release-dockerhub: $@" >&2
}

check()
{
    "$(dirname $0)/check-git-rw" git@github.com "$REPO"
}

prepare()
{
    local version release tmpfile

    WORKDIR="dockerhub"

    trace "Checking out Github repo $SOURCE_REPO"

    rm -rf $WORKDIR
    git clone git@github.com:$SOURCE_REPO $WORKDIR

    trace "Getting version info"

    # Dig out the latest build
    tmpfile=$(mktemp .dockerhub-srpm.XXXXXX)
    LC_ALL=C rpm -qp --info $SRPM > $tmpfile
    version=$(sed -n -e 's/^Version\s*:\s*\(\S\+\).*/\1/p' $tmpfile)
    release=$(sed -n -e 's/^Release\s*:\s*\([0-9]\+\).*/\1/p' $tmpfile)

    if [ -z "$release" -o -z "$version" ]; then
        message "couldn't get version info from SRPM"
        exit 1
    fi

    gitfiles=$(find $WORKDIR -name Dockerfile -printf '%P\n')
    files=$(find $WORKDIR -name Dockerfile)
    sed -i -e "s/ENV VERSION .*/ENV VERSION $version/" \
           -e "s/ENV RELEASE .*/ENV RELEASE $release/" \
           $files

    sed -i -e "s/ARG VERSION/ARG VERSION=$version/" \
           -e "s/ARG RELEASE/ARG RELEASE=$release/" \
           $files

    if git -C $WORKDIR diff --exit-code; then
        trace "Already have correct version in Dockerfile"
        exit 0
    fi

    trace "Committing changes to Dockerfile"

    git -C $WORKDIR commit --message="Update to version $version-$release" $gitfiles
    git -C $WORKDIR tag --annotate --message="Version $version-$release" "$version-$release"

    PUSH="master $version-$release"
    CLEANUP="$CLEANUP $tmpfile"
}

commit()
(
    trace "Pushing changes to Dockerfile"

    if [ "$SOURCE_REPO" == "$REPO" ]; then
        git -C $WORKDIR push origin $PUSH
    else
        git -C $WORKDIR remote add fork "git@github.com:$REPO"
        git -C $WORKDIR push -f fork $PUSH
    fi

    rm $CLEANUP
)

while getopts "s:p:qvxz" opt; do
    case "$opt" in
    s)
        SOURCE_REPO="$OPTARG"
        ;;
    p)
        SRPM="$OPTARG"
        ;;
    q)
        QUIET=1
        VERBOSE=0
        ;;
    v)
        QUIET=0
        VERBOSE=1
        ;;
    x)
        TRANSACTION=1
        ;;
    z)
        CHECK=1
        ;;
    -)
        break
        ;;
    *)
        usage
        ;;
    esac
done

shift $(expr $OPTIND - 1)

if [ $# -ne 1 ]; then
    usage
fi

REPO="$1"
if [ -z "$SOURCE_REPO" ]; then
    SOURCE_REPO="$REPO"
fi

if [ $CHECK -eq 1 ]; then
    check
    exit 0
fi

if [ -z "$SRPM" ]; then
    message "no srpm specified"
    exit 2
elif [ ! -f "$SRPM" ]; then
    message "srpm source not found: $SRPM"
    exit 1
fi

prepare

if [ $TRANSACTION -eq 1 ]; then
    kill -STOP $$
fi

commit
