---
- name: Drop default NTP servers
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^pool'
    state: absent
  register: ntp_1

- name: Add Red Hat internal NTP server
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^server'
    line: server clock.corp.redhat.com iburst
  register: ntp_2

- name: Restart chrony on changes
  service:
    name: chronyd
    state: restarted
  when: ntp_1.changed or ntp_2.changed
