#!/bin/sh

set -ex

if [ -n "$TMPDIR" ]; then
    mkdir -p "$TMPDIR"
fi

if [ ! -d cockpit ]; then
    sudo chown -R user /build
    git clone https://github.com/cockpit-project/cockpit
fi

if [ ! -d cockpit/tools/node_modules ]; then
    ( cd cockpit/tools && npm install )
fi

mkdir -p mock

echo "Starting testing"

while true; do
    fail=0
    find cockpit -name '*.py?' -delete
    git -C cockpit fetch origin master
    git -C cockpit reset --hard FETCH_HEAD
    cockpit/test/vm-download --prune
    if ! cockpit/test/github-task "$@"; then
        fail=1
    fi
    if [ $fail != 0 ]; then
        sleep 60
    fi
done
