#!/bin/sh

set -ex


if [ ! -d cockpit ]; then
    sudo chown -R user /build
    git clone https://github.com/cockpit-project/cockpit
fi

if [ ! -d cockpit/tools/node_modules ]; then
    ( cd cockpit/tools && npm install )
fi

mkdir -p mock

while true; do
	git -C cockpit reset --hard origin/master
	cockpit/test/check-verify --install --rebase "$@"
done
