#!/bin/sh -ex

cd $(dirname $0)
chown user data

if [ ! -e data/bip.pem ]; then
	openssl req -new -newkey rsa:4096 -subj /CN=localhost -nodes -x509 -keyout data/bip.pem -out data/bip.pem
	chown user data/bip.pem
	chmod 600 data/bip.pem
fi

runuser -u user -- /usr/bin/bip -n -f bip.conf -s data
