#!/bin/sh -e

IMAGE=$1
DOCKER=$(which podman docker 2>/dev/null || true)
ID=$($DOCKER images -q $IMAGE:latest | head -n1)

TAGS=$($DOCKER images --format "table {{.Tag}}\t{{.ID}}" $IMAGE | grep $ID | awk '{print $1}')
for PUSHTAG in $TAGS; do
    $DOCKER push "$IMAGE:$PUSHTAG"
done
