---
# Sometimes docker gets itself into a bad state where containers are bad,
# undeletable, or starting/stopping them throws weird storage errors. This
# playbook does a "factory reset". This removes all containers, images,
# and volumes.
- hosts: e2e
  gather_facts: false

  tasks:
  - name: Reset docker
    shell: |
      systemctl stop 'cockpit-tasks@*'
      systemctl stop cockpit-images || true
      systemctl stop docker
      docker-storage-setup --reset
      rm -rf /var/lib/docker
      docker-storage-setup
      systemctl start docker
      systemctl start --all 'cockpit-tasks@*'
      systemctl start cockpit-images || true
