# Deploy secrets from our ci-secrets.git to all tasks runners, including OpenShift
# This uses `oc`, thus you must already be logged into OpenShift.
---
- name: Set up secrets and deploy them to OpenShift
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Clone secrets repository
      git:
        repo: git@gitlab.cee.redhat.com:front-door-ci-wranglers/ci-secrets.git
        # use a directory which is guaranteed to be on tmpfs
        dest: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}/ci-secrets"
        depth: 1

    # copy module is waaaay to slow for recursive directory copy; only upload one tarball
    # we need to resolve symlinks for ../ca.pem due to how container --volumes work
    # also don't include unnecessary secrets, like the CA key or workflow secrets
    - name: Generate secrets archive
      shell: |
        tar -C $XDG_RUNTIME_DIR/ci-secrets  -hz --hard-dereference -c webhook tasks > $XDG_RUNTIME_DIR/ci-secrets.tar.gz
      args:
        # archive module does not support dereferencing links
        warn: false

    - name: Get OpenShift secrets build script
      get_url:
        url: https://raw.githubusercontent.com/cockpit-project/cockpituous/master/tasks/build-secrets
        dest: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}/build-secrets"
        mode: "0755"

    - name: Build OpenShift secrets
      command: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}/build-secrets {{ lookup('env', 'XDG_RUNTIME_DIR') }}/ci-secrets"
      register: build_secrets

    - name: Delete old OpenShift secrets
      command:
        cmd: "{{ oc_command }} delete --ignore-not-found=true -f -"
        stdin: "{{ build_secrets.stdout }}"

    - name: Create new secrets
      command:
        cmd: "{{ oc_command }} create -f -"
        stdin: "{{ build_secrets.stdout }}"

    - name: Restart image pods to pick up changed certificates
      shell: "{{ oc_command }} get -o name -l infra=cockpit-images pods | xargs -l -r {{ oc_command }} delete --wait=false"

- name: Deploy secrets to e2e and AWS
  hosts: e2e tag_ServiceName_FrontDoorCI
  gather_facts: false
  tasks:
    - name: Upload secrets
      copy:
        src: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}/ci-secrets.tar.gz"
        dest: /tmp/secrets.tar.gz
        mode: '0600'

    - name: Clean up old secrets directory
      file:
        path: /var/lib/cockpit-secrets
        state: absent

    - name: Set up secrets dir
      file:
        path: /var/lib/cockpit-secrets
        owner: '1111'
        group: '1111'
        state: directory
        setype: container_file_t

    - name: Unarchive secrets
      unarchive:
        src: /tmp/secrets.tar.gz
        remote_src: true
        dest: /var/lib/cockpit-secrets/
        owner: '1111'
        group: '1111'
        setype: container_file_t

    # otherwise ssh bitterly complains: Permissions 0644 for '/secrets/id_rsa' are too open
    - name: Fix permissions of private SSH key file
      file:
        path: /var/lib/cockpit-secrets/tasks/id_rsa
        mode: '0600'

    - name: Clean up secrets archive
      file:
        path: /tmp/secrets.tar.gz
        state: absent

    # the above empties the /secrets volume for running containers
    - name: Restart image containers to pick up changed secrets
      # The glob avoids failure on machines which are not running cockpit-images
      command: systemctl restart cockpit-images*.service
