# Deploy secrets from our ci-secrets.git to all tasks runners, including OpenShift
# This uses `oc`, thus you must already be logged into OpenShift.
---
- name: Deploy secrets to OpenShift
  hosts: localhost
  gather_facts: false
  roles:
    - install-secrets-openshift

- name: Deploy secrets to cloud instances
  hosts: tag_ServiceName_FrontDoorCI openstack_tasks
  gather_facts: false
  roles:
    - install-secrets-dir
    - local-s3-alias
