---
 - name: Build OpenShift secrets
   command: "{{ role_path }}/../../../tasks/build-secrets {{ lookup('env', 'XDG_RUNTIME_DIR') }}/ci-secrets"
   register: build_secrets

 - name: Update deployed secrets
   command:
     cmd: "{{ oc_command }} apply -f -"
     stdin: "{{ build_secrets.stdout }}"

 - name: Restart all containers to pick up new secrets
   shell: "{{ oc_command }} get -o name pods | xargs -l -r {{ oc_command }} delete --wait=false"
