name: build-images
on:
  # this is meant to be run on an approved PR branch for convenience
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    environment: quay.io
    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Log into container registry
        run: podman login -u ${{ secrets.QUAY_BOTUSER }} -p ${{ secrets.QUAY_TOKEN }} quay.io

      - name: Build images container
        run: make images-container

      - name: Push container to registry
        run: make images-push
