# Expose our test-results.db database and CI weather (https://github.com/cockpit-project/bots/blob/main/tests.html)
# on a simple web server. Grafana still does not fully replace this.

kind: ReplicationController
apiVersion: v1
metadata:
  name: ci-weather
spec:
  replicas: 1
  selector:
    infra: ci-weather
  template:
    metadata:
      name: ci-weather
      labels:
        infra: ci-weather
    spec:
      containers:
        - name: ci-weather
          image: docker.io/nginxinc/nginx-unprivileged
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
          - name: prometheus-data
            mountPath: /usr/share/nginx/html/
            readOnly: true
          resources:
            limits:
              memory: 1G
              cpu: 1
            requests:
              memory: 200M
              cpu: 100m
      volumes:
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data

---
kind: Service
apiVersion: v1
metadata:
  name: ci-weather-http
spec:
  clusterIP: None
  selector:
    infra: ci-weather
  ports:
  # we use edge termination, so talk to plain http
  - targetPort: http
    port: 443
    protocol: TCP
    name: http

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ci-weather
spec:
  to:
    kind: Service
    name: ci-weather-http
  port:
    targetPort: http
  tls:
    termination: edge
